// Copyright 2020-2021 Gnosis Ltd.
// Copyright 2015-2020 Parity Technologies (UK) Ltd.
// This file is part of OpenEthereum.

// OpenEthereum is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// OpenEthereum is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with OpenEthereum.  If not, see <http://www.gnu.org/licenses/>.

//! Chain Frozen State
//!
//! Provides a way for blockchains to "freeze" a given set of historical
//! transactions by hardcoding the outcome of their executions.
//!
//! When a fronzen transaction is encountered on the blockchain, it will not
//! be executed by the VM against the latest world state, the hardcoded balance
//! and storage changes will be applied insead without touching the actual code.
//!
//! The scenario that brought up the need for this feature was disabling the WASM
//! VM engine. At the time of writing the Kovan Testnet had several hundred transactions
//! that invoked the WASM VM.
//!
//! This feature is used to store the historical results of
//! old known transactinos prior to disabling and removing WASM so that the chain could
//! still function and sync old blocks with the pWASM engine code removed from the codebase.
//!
//! Other use cases for this feature might be to speed up the import of known slow historic
//! blocks that were a result of DDoS attacks in the past.
//!
//! The structure of a single frozen transaction in a given block, with changes
//! to the balances and storage values, returning receipts with logs looks as following:
//!
//! ```json
//! "7103749": [ // block number
//!   {
//!     "id": "b127f7d546309857bcc5d03b4532e641749e196f7cdcb45789b914f989dbc8cd", // transaction id
//!     "balanceOps": [
//!       {
//!         "account": "0x05ba9a1d453ed591f70e5884a5eded482400bb62",
//!         "amount": "0x642fc026aa8000",
//!         "op": "sub"
//!       },
//!       {
//!         "account": "0x05ba9a1d453ed591f70e5884a5eded482400bb62",
//!         "amount": "0x60bd080aa20000",
//!         "op": "add"
//!       }
//!     ],
//!     "storageChanges": [
//!        {
//!           "account": "0xfe3552a8444c54a9b3d79cf890063d345562ea9d",
//!           "key": "0x20000000000000000000000000000000000000000000000000000000000000",
//!           "value": "0x98968"
//!         },
//!         {
//!           "account": "0xfe3552a8444c54a9b3d79cf890063d345562ea9d",
//!           "key": "0x1000000000000000000000005ba9a1d453ed591f70e5884a5eded482400bb6",
//!           "value": "0x98968"
//!         },
//!         {
//!           "account": "0xfe3552a8444c54a9b3d79cf890063d345562ea9d",
//!           "key": "0x30000000000000000000000000000000000000000000000000000000000000",
//!           "value": "0x5ba9a1d453ed591f70e5884a5eded482400bb6"
//!         }
//!       ],
//!     "receipt": {
//!       "gasUsed": "0x7e60",
//!       "logBloom": "dbc9c830d20100", // hex(deflate_bytes(logs_bloom))
//!       "logs": [
//!         {
//!           "address": "0xfe3552a8444c54a9b3d79cf890063d345562ea9d",
//!           "topics": [
//!             "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
//!             "0x00000000000000000000000005ba9a1d453ed591f70e5884a5eded482400bb62",
//!             "0x00000000000000000000000000859735759eede1232fb2567254d0e69c89d542"
//!           ],
//!           "data": "0x00000000000000000000000000000000000000000000000000000000000000c8"
//!         }
//!       ],
//!       "outcome": {
//!         "StatusCode": 1
//!       }
//!     }
//!   }
//! ],
//! ```

use ethereum_types::{Address, H256, U256};
use std::{collections::BTreeMap, ops::Deref, str::FromStr};

/// Encapsulates all possible effects a transaction
/// execution may have on the world state.
#[serde(rename_all = "camelCase")]
#[derive(Debug, Deserialize)]
pub struct TransactionTrace {
    /// Globally unique transaction hash
    pub id: H256,

    /// Changes to any balances in accounts caused by a transaction
    /// This also includes transfer of gas fees to the miner.
    pub balance_ops: Vec<BalanceOp>,

    /// All key-value pairs in account state trees that are set
    /// as a result of running this transaction.
    pub storage_changes: Vec<StorageChange>,

    /// All logs/events generated by this transaction.
    pub receipt: common_types::receipt::TypedReceipt,
}

/// defines whether an account balance increases
/// or decreases by a given amount
#[serde(rename_all = "camelCase")]
#[derive(Debug, Eq, PartialEq, Deserialize)]
pub enum Op {
    Add,
    Sub,
}

/// represents a single change in balance
/// for an account, relative to its prior value
/// before running the transaction.
#[serde(rename_all = "camelCase")]
#[derive(Debug, Deserialize)]
pub struct BalanceOp {
    pub account: Address,
    pub amount: U256,
    pub op: Op,
}

/// defines the equivalent of one SSTORE operation
/// that sets one key to a 256 bit value at a given
/// contract state subtree.
#[serde(rename_all = "camelCase")]
#[derive(Debug, Deserialize)]
pub struct StorageChange {
    /// Address of the contract owning the state
    pub account: Address,

    /// a 256 bit key in the contract storage address space.
    pub key: H256,

    /// a 256 bit (32 byte) arbitary value stored under key
    /// in account's state tree.
    pub value: U256,
}

/// Key is the block number, and the value is a list of transactions
/// within that block with the results of their execution. The assumption
/// is that all values are always sorted by the block number and tx chronologically.
struct FrozenChainState(BTreeMap<u64, Vec<TransactionTrace>>);

impl Deref for FrozenChainState {
    type Target = BTreeMap<u64, Vec<TransactionTrace>>;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl FromStr for FrozenChainState {
    type Err = serde_json::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Ok(FrozenChainState(serde_json::from_str(s)?))
    }
}

#[cfg(test)]
mod tests {
    use std::str::FromStr;

    use common_types::receipt::{TransactionOutcome, TypedReceipt};
    use ethereum_types::Bloom;

    use super::*;

    #[test]
    fn can_deserialize_frozen_block() {
        let serialized_block = r#"{
            "9340615": [
                {
                  "id": "0xbcba4ff3e38eeb3da6dddae4a0fdd264191e62582767db60a0798cae89dabbc5",
                  "balanceOps": [
                    {
                      "account": "0x4af013afbadb22d8a88c92d68fc96b033b9ebb8a",
                      "amount": "0x5af3107a40000",
                      "op": "sub"
                    },
                    {
                      "account": "0x4af013afbadb22d8a88c92d68fc96b033b9ebb8a",
                      "amount": "0x5779b95c67200",
                      "op": "add"
                    },
                    {
                      "account": "0x0020ee4be0e2027d76603cb751ee069519ba81a1",
                      "amount": "0x379571dd8e00",
                      "op": "add"
                    }            
                  ],
                  "storageChanges": [
                    {
                      "account": "0xc6004fbd8437201472f6d6dff362dbc4233f03f1",
                      "key": "0x00100000000000000000000004af013afbadb22d8a88c92d68fc96b033b9ebb8",
                      "value": "0x98929"
                    },
                    {
                      "account": "0xc6004fbd8437201472f6d6dff362dbc4233f03f1",
                      "key": "0x0010000000000000000000000cafe0854989c15301de5cf580a39015de48df4f",
                      "value": "0x3e"
                    }            
                  ],
                  "receipt": {
                    "legacy": {
                      "gasUsed": "0x655db",
                      "logBloom": "0x63a018088011107060cab16088303230382034c20107f9f633326111644258831f0000",
                      "logs": [
                        {
                          "address": "0xc6004fbd8437201472f6d6dff362dbc4233f03f1",
                          "topics": [
                            "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
                            "0x0000000000000000000000004af013afbadb22d8a88c92d68fc96b033b9ebb8a",
                            "0x000000000000000000000000cafe0854989c15301de5cf580a39015de48df4f8"
                          ],
                          "data": "0x00000000000000000000000000000000000000000000000000000000000003e8"
                        }
                      ],
                      "outcome": {
                        "statusCode": 1
                      }
                    }
                  }
                }            
              ]
        }"#;

        let deserialized = FrozenChainState::from_str(&serialized_block).unwrap();
        assert_eq!(deserialized.len(), 1);

        let known_block = deserialized.get(&9340615u64);
        assert_eq!(known_block.is_some(), true);

        if let Some(transactions) = known_block {
            assert_eq!(transactions.len(), 1);

            let tx = transactions.first();
            assert_eq!(tx.is_some(), true);

            if let Some(tx) = tx {
                assert_eq!(
                    tx.id,
                    H256::from_str(
                        "bcba4ff3e38eeb3da6dddae4a0fdd264191e62582767db60a0798cae89dabbc5"
                    )
                    .unwrap()
                );

                assert_eq!(
                    tx.balance_ops[0].account,
                    Address::from_str("4af013afbadb22d8a88c92d68fc96b033b9ebb8a").unwrap()
                );
                assert_eq!(
                    tx.balance_ops[0].amount,
                    U256::from_str("5af3107a40000").unwrap()
                );
                assert_eq!(tx.balance_ops[0].op, Op::Sub);

                assert_eq!(
                    tx.balance_ops[1].account,
                    Address::from_str("4af013afbadb22d8a88c92d68fc96b033b9ebb8a").unwrap()
                );
                assert_eq!(
                    tx.balance_ops[1].amount,
                    U256::from_str("5779b95c67200").unwrap()
                );
                assert_eq!(tx.balance_ops[1].op, Op::Add);

                assert_eq!(
                    tx.balance_ops[2].account,
                    Address::from_str("0020ee4be0e2027d76603cb751ee069519ba81a1").unwrap()
                );
                assert_eq!(
                    tx.balance_ops[2].amount,
                    U256::from_str("379571dd8e00").unwrap()
                );
                assert_eq!(tx.balance_ops[2].op, Op::Add);

                assert_eq!(
                    tx.storage_changes[0].account,
                    Address::from_str("c6004fbd8437201472f6d6dff362dbc4233f03f1").unwrap()
                );

                assert_eq!(
                    tx.storage_changes[0].key,
                    H256::from_str(
                        "00100000000000000000000004af013afbadb22d8a88c92d68fc96b033b9ebb8"
                    )
                    .unwrap()
                );

                assert_eq!(
                    tx.storage_changes[0].value,
                    U256::from_str("98929").unwrap()
                );

                assert_eq!(
                    tx.storage_changes[1].account,
                    Address::from_str("c6004fbd8437201472f6d6dff362dbc4233f03f1").unwrap()
                );

                assert_eq!(
                    tx.storage_changes[1].key,
                    H256::from_str(
                        "0010000000000000000000000cafe0854989c15301de5cf580a39015de48df4f"
                    )
                    .unwrap()
                );

                assert_eq!(tx.storage_changes[1].value, U256::from_str("3e").unwrap());

                if let TypedReceipt::Legacy(ref receipt) = tx.receipt {
                    assert_eq!(receipt.gas_used, U256::from_str("655db").unwrap());
                    assert_eq!(receipt.outcome, TransactionOutcome::StatusCode(1));
                    assert_eq!(receipt.logs.len(), 1);
                    assert_eq!(receipt.log_bloom, Bloom::from_str("00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000010000000000008000000000000000000000000000000000000040000000000000000000000000000000000010000400000000000000010000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000102000000000000000000000000000000000000000200004000000000000000000000000000000000000000000000000000000000000000000000000000").unwrap());

                    assert_eq!(
                        receipt.logs[0].address,
                        Address::from_str("c6004fbd8437201472f6d6dff362dbc4233f03f1").unwrap()
                    );
                    assert_eq!(receipt.logs[0].topics.len(), 3);

                    assert_eq!(
                        receipt.logs[0].topics[0],
                        H256::from_str(
                            "ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"
                        )
                        .unwrap()
                    );
                    assert_eq!(
                        receipt.logs[0].topics[1],
                        H256::from_str(
                            "0000000000000000000000004af013afbadb22d8a88c92d68fc96b033b9ebb8a"
                        )
                        .unwrap()
                    );
                    assert_eq!(
                        receipt.logs[0].topics[2],
                        H256::from_str(
                            "000000000000000000000000cafe0854989c15301de5cf580a39015de48df4f8"
                        )
                        .unwrap()
                    );

                    assert_eq!(
                        receipt.logs[0].data,
                        vec![
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 3, 232
                        ]
                    );
                } else {
                    assert!(false);
                }
            }
        }
    }
}
